version: '2'

services:
  mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=test
    volumes:
      - ./backup:/var/backup

  redis:
    image: redis:latest

  php:
    build: docker/php
    volumes:
      - ./:/var/www
      - ~/.composer:/root/.composer
      - ./docker/php/docker-vars.ini:/usr/local/etc/php/conf.d/docker-vars.ini